In [1]:
import numpy as np

In [2]:
from sklearn.datasets import load_iris

In [3]:
iris = load_iris()

In [4]:
type(iris)

sklearn.utils.Bunch

In [5]:
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [6]:
X = iris.data
#X

In [7]:
y = iris.target

# y  has class 0, 1, and 2.  Want to convert to categorical (one hot encoded)
# class 0 --> [1,0,0]
# class 1 --> [0,1,0]
# class 2 --> [0,0,1]

In [8]:
from keras.utils import to_categorical

In [9]:
y = to_categorical(y)

In [10]:
y.shape

(150, 3)

In [12]:
#y

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [19]:
#y_test

In [20]:
#good to scale or standardize data for NN
from sklearn.preprocessing import MinMaxScaler #scales all values between 0 and 1

In [21]:
scaler_object = MinMaxScaler()

In [25]:
#np.array([5,10,15,20])/20  example of what we're doing with MinMaxScaler

In [26]:
scaler_object.fit(X_train) #fit on only training data as don't want to assume prior knowledge of test data

MinMaxScaler(copy=True, feature_range=(0, 1))

In [27]:
scaled_X_train = scaler_object.transform(X_train)

In [28]:
scaled_X_test = scaler_object.transform(X_test)

In [34]:
#X_train

In [30]:
#scaled_X_train when look now all b/w 0 and 1

In [31]:
#now build network with keras
from keras.models import Sequential
from keras.layers import Dense

In [35]:
model = Sequential() #create sequential model
model.add(Dense(8, input_dim=4, activation='relu')) #add layers (each has different parameters) 8 neurons -> 2X number of features (usually a multiple)
model.add(Dense(8, input_dim=4, activation='relu'))
model.add(Dense(3, activation='softmax')) #each of 3 neurons will have a probability for belonging to a class (of one hot)
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy']) #cause categorical data

Instructions for updating:
Colocations handled automatically by placer.


In [36]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 8)                 40        
_________________________________________________________________
dense_2 (Dense)              (None, 8)                 72        
_________________________________________________________________
dense_3 (Dense)              (None, 3)                 27        
Total params: 139
Trainable params: 139
Non-trainable params: 0
_________________________________________________________________


In [37]:
model.fit(scaled_X_train, y_train, epochs=150, verbose=2) #verbose gives you info

Instructions for updating:
Use tf.cast instead.
Epoch 1/150
 - 0s - loss: 1.1287 - accuracy: 0.6600
Epoch 2/150
 - 0s - loss: 1.1157 - accuracy: 0.6600
Epoch 3/150
 - 0s - loss: 1.1035 - accuracy: 0.6500
Epoch 4/150
 - 0s - loss: 1.0918 - accuracy: 0.6600
Epoch 5/150
 - 0s - loss: 1.0801 - accuracy: 0.6600
Epoch 6/150
 - 0s - loss: 1.0676 - accuracy: 0.6600
Epoch 7/150
 - 0s - loss: 1.0565 - accuracy: 0.6600
Epoch 8/150
 - 0s - loss: 1.0445 - accuracy: 0.6600
Epoch 9/150
 - 0s - loss: 1.0328 - accuracy: 0.6600
Epoch 10/150
 - 0s - loss: 1.0204 - accuracy: 0.6600
Epoch 11/150
 - 0s - loss: 1.0077 - accuracy: 0.6600
Epoch 12/150
 - 0s - loss: 0.9948 - accuracy: 0.6600
Epoch 13/150
 - 0s - loss: 0.9812 - accuracy: 0.6600
Epoch 14/150
 - 0s - loss: 0.9676 - accuracy: 0.6600
Epoch 15/150
 - 0s - loss: 0.9539 - accuracy: 0.6600
Epoch 16/150
 - 0s - loss: 0.9397 - accuracy: 0.6600
Epoch 17/150
 - 0s - loss: 0.9255 - accuracy: 0.6600
Epoch 18/150
 - 0s - loss: 0.9112 - accuracy: 0.6600
Epoch 1

Epoch 150/150
 - 0s - loss: 0.3260 - accuracy: 0.9400


#predict on new data, and measure performance

In [40]:
#we have scaled data already- if have new data, will have to scale it 
#model.predict(scaled_X_test) #spits out probabilities
model.predict_classes(scaled_X_test) #predict classes, not one hot encoded, just index position

array([1, 0, 2, 1, 2, 0, 1, 2, 2, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 2, 2, 1, 2], dtype=int64)

In [41]:
#compare predictions to y_test
predictions = model.predict_classes(scaled_X_test)

In [42]:
y_test.argmax(axis = 1) #transform y_test data, reports back actual classes cause max value at index of corresponding class

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 2, 2, 1, 2], dtype=int64)

In [43]:
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

In [44]:
confusion_matrix(y_test.argmax(axis=1), predictions)

array([[19,  0,  0],
       [ 0, 13,  2],
       [ 0,  0, 16]], dtype=int64)

In [45]:
print(classification_report(y_test.argmax(axis=1), predictions))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      0.87      0.93        15
           2       0.89      1.00      0.94        16

    accuracy                           0.96        50
   macro avg       0.96      0.96      0.96        50
weighted avg       0.96      0.96      0.96        50



In [46]:
print(accuracy_score(y_test.argmax(axis=1), predictions))

0.96


In [47]:
#to be able to save and load model
model.save('myfirstmodel.h5') #saves all weights of network so can quickly load again

In [48]:
#to load
from keras.models import load_model

In [49]:
new_model = load_model('myfirstmodel.h5') #make sure to call from right location, be careful of naming scheme, as this overwrites other h5 files


In [50]:
new_model.predict_classes(scaled_X_test) #can then pass in data, run, and get classes predicted

array([1, 0, 2, 1, 2, 0, 1, 2, 2, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 2, 2, 1, 2], dtype=int64)