In [1]:
import pandas as pd

In [2]:
npr = pd.read_csv('npr.csv')

In [3]:
npr.head()

Article
0  In the Washington of 2016, even when the polic...
1    Donald Trump has used Twitter  —   his prefe...
2    Donald Trump is unabashedly praising Russian...
3  Updated at 2:50 p. m. ET, Russian President Vl...
4  From photography, illustration and video, to d...

In [7]:
#to see article, index row
#print(npr['Article'][1])

#to see how many articles
len(npr)

11992

# before LDA, need to do some preprocessing

In [8]:
from sklearn.feature_extraction.text import CountVectorizer

In [9]:
cv = CountVectorizer(max_df=0.9, min_df=2, stop_words='english') #max_df ignores terms with high document freq (really common, e.g. show up in 90% of docs)
#can do max and min df either as proportion, or integer for actual number of docs
#countvectorizer can also remove stopwords

In [10]:
#no train test split, since unsupervised.  So fittransform to all data


In [11]:
dtm = cv.fit_transform(npr['Article'])

In [13]:
dtm #should be a sparse matrix

<11992x54777 sparse matrix of type '<class 'numpy.int64'>'
	with 3033388 stored elements in Compressed Sparse Row format>

In [14]:
#get 54,777 terms in teh 11,992 articles

In [15]:
from sklearn.decomposition import LatentDirichletAllocation

In [16]:
LDA = LatentDirichletAllocation(n_components=7, random_state=42)

In [17]:
LDA.fit(dtm)

LatentDirichletAllocation(batch_size=128, doc_topic_prior=None,
                          evaluate_every=-1, learning_decay=0.7,
                          learning_method='batch', learning_offset=10.0,
                          max_doc_update_iter=100, max_iter=10,
                          mean_change_tol=0.001, n_components=7, n_jobs=None,
                          perp_tol=0.1, random_state=42, topic_word_prior=None,
                          total_samples=1000000.0, verbose=0)

In [18]:
#it iterates through each word in each doc, so will take a while

In [19]:
# 3 steps left
# Grab vocabulary of words

# Grab the topics

# Grab the highest probability words per topic

In [25]:
# Grab vocab of words
len(cv.get_feature_names())

54777

In [27]:
type(cv.get_feature_names())

list

In [30]:
# getting words at index locations
cv.get_feature_names()[41000]

'reproductive'

In [34]:
# to print out a list of a random bunch of words from the list

import random

random_word_id = random.randint(0, 54777)
cv.get_feature_names()[random_word_id] #generates a random index number

'somber'

In [ ]:
# Grab the topics


In [35]:
len(LDA.components_)

7

In [ ]:
# number of components I specified

In [36]:
type(LDA.components_)

numpy.ndarray

In [37]:
LDA.components_.shape # componenents by number of words

(7, 54777)

In [39]:
LDA.components_ #generates a giant array

array([[8.64332806e+00, 2.38014333e+03, 1.42900522e-01, ...,
        1.43006821e-01, 1.42902042e-01, 1.42861626e-01],
       [2.76191749e+01, 5.36394437e+02, 1.42857148e-01, ...,
        1.42861973e-01, 1.42857147e-01, 1.42906875e-01],
       [7.22783888e+00, 8.24033986e+02, 1.42857148e-01, ...,
        6.14236247e+00, 2.14061364e+00, 1.42923753e-01],
       ...,
       [3.11488651e+00, 3.50409655e+02, 1.42857147e-01, ...,
        1.42859912e-01, 1.42857146e-01, 1.42866614e-01],
       [4.61486388e+01, 5.14408600e+01, 3.14281373e+00, ...,
        1.43107628e-01, 1.43902481e-01, 2.14271779e+00],
       [4.93991422e-01, 4.18841042e+02, 1.42857151e-01, ...,
        1.42857146e-01, 1.43760101e-01, 1.42866201e-01]])

In [40]:
single_topic = LDA.components_[0]

In [41]:
single_topic.argsort() #don't know what topic represents, argsort returns index positions that would sort this array

array([ 2475, 18302, 35285, ..., 22673, 42561, 42993], dtype=int64)

# Aside to understand argsort

In [42]:
import numpy as np

In [43]:
arr = np.array([10, 200, 1])

In [45]:
arr.argsort() # these are index positions that would sort array from lowest to highest (shows index posisitions of larger values)

array([2, 0, 1], dtype=int64)

# Back to main show

In [49]:
single_topic.argsort()[-10:] 
#grabs top 10 words (highest counts)  grabs last 10 values of argsort.  returns index positions
# Top 10 values --> last 10 values of argsort

array([33390, 36310, 21228, 10425, 31464,  8149, 36283, 22673, 42561,
       42993], dtype=int64)

In [50]:
top_ten_words = single_topic.argsort()[-10:]

In [52]:
for index in top_ten_words:
    print(cv.get_feature_names()[index]) #10 highest proba words in first topic

new
percent
government
company
million
care
people
health
said
says


In [53]:
top_twenty_words = single_topic.argsort()[-20:]
for index in top_twenty_words:
    print(cv.get_feature_names()[index]) #20 highest proba words in first topic

president
state
tax
insurance
trump
companies
money
year
federal
000
new
percent
government
company
million
care
people
health
said
says


In [ ]:
# Grab the highest probability words per topic


In [54]:
for i, topic in enumerate(LDA.components_):
    print(f"The top 15 words for Topic #{i}")
    print([cv.get_feature_names()[index] for index in topic.argsort()[-15:]])
    print('\n')
    print('\n')

The top 15 words for Topic #0
['companies', 'money', 'year', 'federal', '000', 'new', 'percent', 'government', 'company', 'million', 'care', 'people', 'health', 'said', 'says']




The top 15 words for Topic #1
['military', 'house', 'security', 'russia', 'government', 'npr', 'reports', 'says', 'news', 'people', 'told', 'police', 'president', 'trump', 'said']




The top 15 words for Topic #2
['way', 'world', 'family', 'home', 'day', 'time', 'water', 'city', 'new', 'years', 'food', 'just', 'people', 'like', 'says']




The top 15 words for Topic #3
['time', 'new', 'don', 'years', 'medical', 'disease', 'patients', 'just', 'children', 'study', 'like', 'women', 'health', 'people', 'says']




The top 15 words for Topic #4
['voters', 'vote', 'election', 'party', 'new', 'obama', 'court', 'republican', 'campaign', 'people', 'state', 'president', 'clinton', 'said', 'trump']




The top 15 words for Topic #5
['years', 'going', 've', 'life', 'don', 'new', 'way', 'music', 'really', 'time', 'know'

# now last thing, attached topic numbers to original articles

In [55]:
topic_results = LDA.transform(dtm)

In [58]:
topic_results.shape #number of articles with probabilities of each topic

(11992, 7)

In [60]:
topic_results[1].round(2)

array([0.04, 0.89, 0.  , 0.  , 0.08, 0.  , 0.  ])

In [ ]:
#most probably topic 1 - the one about trump (see article up top)

In [61]:
#now connect back to original dataframe
#use ARGMAX to return index position of highest probability

In [62]:
npr['Topic'] = topic_results.argmax(axis = 1)

In [64]:
npr.head(15)

Article  Topic
0   In the Washington of 2016, even when the polic...      1
1     Donald Trump has used Twitter  —   his prefe...      1
2     Donald Trump is unabashedly praising Russian...      1
3   Updated at 2:50 p. m. ET, Russian President Vl...      1
4   From photography, illustration and video, to d...      2
5   I did not want to join yoga class. I hated tho...      3
6   With a   who has publicly supported the debunk...      3
7   I was standing by the airport exit, debating w...      2
8   If movies were trying to be more realistic, pe...      3
9   Eighteen years ago, on New Year’s Eve, David F...      2
10  For years now, some of the best, wildest, most...      5
11  For years now, some of the best, wildest, most...      5
12  The Colorado River is like a giant bank accoun...      2
13  For the last installment of NPR’s holiday reci...      2
14  Being overweight can raise your blood pressure...      3